os: linux
dist: jammy
services:
  - docker
install: skip
before_install:
  - docker version
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker
  - docker version
